# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # VM Configuration
  #
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise32"
  
  # Configuring Provisioning
  #
  # Adding Bootstrap for automated installation on first Start
  # Adds the Script after-boot.sh to be run on each System Start
  config.vm.provision :shell, path: "bootstrap.sh" 
  config.vm.provision "shell", path: "after-boot.sh", run: "always"

  # Network Configuration
  #
  # Fowards Ports. Host is the Port seen on Host Computer, guest is the Port used by the VM
  # Configures the Local Network IP 192.168.50.50 to be the VM
  config.vm.network :forwarded_port, host: 80, guest: 80
  config.vm.network :private_network, ip: '192.168.50.50'

  # Configuration for Virtual Machine
  #
  # Creates fix, so Symlinks work as long as Executed as Administrator
  # Configures 2048 MB Ram for the VM
  # Configures 2 CPU Cores for the VM
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
  end
  
  # Sync Folder Configuration
  #
  # Create a Sync Folder "vhosts" for the VM Dir /etc/apache2/sites-available with owner root
  # Create a Sync Folder "www" for the VM Dir /var/www with owner www-data
  config.vm.synced_folder "vhosts/", "/etc/apache2/sites-available",
    owner: "root", group: "root"
  config.vm.synced_folder "www/", "/var/www",
    owner: "www-data", group: "www-data"

end
